# Generated by Django 5.0.3 on 2024-03-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
