# Generated by Django 5.0.3 on 2024-03-16 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0002_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('keyword', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='registerNumber',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='keyword',
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[("3rd year bachelor's degree", 'L3'), ("2nd year master's degree", 'M2')], default='L3', max_length=40),
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[("3rd year bachelor's degree", 'L3'), ("2nd year master's degree", 'M2')], default='L3', max_length=40),
        ),
        migrations.AddField(
            model_name='subject',
            name='proposer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionpfe_app.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='valable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='belongs',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionpfe_app.department'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('student', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionpfe_app.student')),
                ('subject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionpfe_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('department', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionpfe_app.department')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='speciality',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionpfe_app.speciality'),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionpfe_app.speciality'),
        ),
    ]
