# Generated by Django 5.0.3 on 2024-03-29 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0003_department_remove_student_registernumber_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='proposer',
        ),
        migrations.AddField(
            model_name='subject',
            name='keyword',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('External end-of-studies project', 'External'), ('Internal end-of-studies project', ' Internal')], default='Internal', max_length=40),
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
