# Generated by Django 5.0.3 on 2024-03-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0004_remove_department_keyword_remove_subject_proposer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='keyword',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
