# Generated by Django 5.0.3 on 2024-04-18 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0005_teacher_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='doyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionpfe_app.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='binome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binome_of', to='gestionpfe_app.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='valable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BinomeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binome_request_receiver', to='gestionpfe_app.student')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binome_request_sender', to='gestionpfe_app.student')),
            ],
        ),
    ]
