# Generated by Django 5.0.3 on 2024-04-19 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0006_department_doyen_student_binome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinomeSubjectChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_for_binomes', to='gestionpfe_app.subject')),
                ('binome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_choices', to='gestionpfe_app.student')),
                ('subjects', models.ManyToManyField(related_name='chosen_by_binomes', to='gestionpfe_app.subject')),
            ],
        ),
    ]
