# Generated by Django 5.0.3 on 2024-04-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0007_binomesubjectchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('External', 'External end-of-studies project'), ('Internal', 'Internal end-of-studies project')], default='Internal', max_length=40),
        ),
    ]
