# Generated by Django 5.0.3 on 2024-04-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0009_defensesession_subject_teacher_alter_subject_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='subject',
            name='keyword',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
