# Generated by Django 5.0.3 on 2024-05-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestionpfe_app', '0010_alter_subject_description_alter_subject_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='creator_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='creator_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='keyword',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
