# Generated by Django 5.0.3 on 2024-05-17 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0011_subject_creator_id_subject_creator_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defense',
            name='teacher',
        ),
        migrations.AddField(
            model_name='defense',
            name='teacher1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jury1', to='gestionpfe_app.teacher'),
        ),
        migrations.AddField(
            model_name='defense',
            name='teacher2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jury2', to='gestionpfe_app.teacher'),
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionpfe_app.student')),
                ('subject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionpfe_app.subject')),
            ],
        ),
    ]
