# Generated by Django 5.0.3 on 2024-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0012_remove_defense_teacher_defense_teacher1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectchoice',
            name='teacheraprove',
            field=models.BooleanField(default=False),
        ),
    ]
