# Generated by Django 5.0.3 on 2024-05-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0014_alter_subjectchoice_teacheraprove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectchoice',
            name='teacheraprove',
            field=models.CharField(choices=[('', ''), ('allowed', 'allowed'), ('not-allowed', 'not-allowed')], default='', max_length=40),
        ),
    ]
