# Generated by Django 5.0.3 on 2024-05-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0016_alter_subjectchoice_teacheraprove'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='nb_approve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='nb_reject',
            field=models.IntegerField(default=0),
        ),
    ]
