# Generated by Django 5.0.3 on 2024-05-18 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0017_subject_nb_approve_subject_nb_reject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpfe_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpfe_app.teacher')),
            ],
            options={
                'unique_together': {('subject', 'teacher')},
            },
        ),
    ]
