# Generated by Django 5.0.3 on 2024-05-18 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0019_remove_subject_nb_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='last_rejector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_rejected_subjects', to='gestionpfe_app.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='nb_reject',
            field=models.IntegerField(default=0),
        ),
    ]
