# Generated by Django 5.0.3 on 2024-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0020_subject_last_rejector_subject_nb_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectinteraction',
            name='action',
            field=models.CharField(choices=[('approved', 'Approved')], max_length=10),
        ),
    ]
