# Generated by Django 5.0.3 on 2024-05-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0021_alter_subjectinteraction_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='last_rejector',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='nb_approve',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='nb_reject',
        ),
        migrations.AddField(
            model_name='subject',
            name='validation_commission',
            field=models.ManyToManyField(related_name='validation_commissions', to='gestionpfe_app.teacher'),
        ),
        migrations.AlterField(
            model_name='subjectinteraction',
            name='action',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10),
        ),
    ]
