# Generated by Django 5.0.3 on 2024-05-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0022_remove_subject_last_rejector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matricule',
            field=models.CharField(default=0, max_length=40, unique=True),
        ),
    ]
