# Generated by Django 5.0.3 on 2024-05-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0024_defensesession_level_result_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='defense',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='gestionpfe_app.defense'),
        ),
    ]
