# Generated by Django 5.0.3 on 2024-05-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0026_remove_defense_defense_result_defense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defense',
            name='teacher1',
        ),
        migrations.RemoveField(
            model_name='defense',
            name='teacher2',
        ),
        migrations.AddField(
            model_name='defense',
            name='teachers',
            field=models.ManyToManyField(related_name='defenses', to='gestionpfe_app.teacher'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
