# Generated by Django 5.0.3 on 2024-05-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0027_remove_defense_teacher1_remove_defense_teacher2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivi',
            name='student',
        ),
    ]
