# Generated by Django 5.0.3 on 2024-05-23 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe_app', '0029_remove_result_student_remove_result_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectchoice',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='suivi',
            name='subject',
        ),
        migrations.AddField(
            model_name='suivi',
            name='choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionpfe_app.subjectchoice'),
        ),
    ]
